# Generated by Django 4.2.4 on 2023-08-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('dc_user', models.BigIntegerField(verbose_name='DC ID of user')),
                ('ping_count', models.IntegerField(default=0, verbose_name='Number of pings')),
                ('last_ping', models.DateTimeField(auto_now=True, verbose_name='Last ping')),
            ],
        ),
    ]
